# Navigation Links
main:
  - name: Bio
    url: /
    weight: 10
    
  - name: EXTRACURRICULAR ACTIVITIES
    url: /#experience
    weight: 20

  - name: AWARDS
    url: /#accomplishments
    weight: 30
